package com.luffy.design_pattern.opt.refractor;

import com.google.common.annotations.VisibleForTesting;
import com.luffy.design_pattern.opt.IdGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.InetAddress;
import java.net.UnknownHostException;

/*
  随机id生成器
  <p>
  一、提高代码的可读性
  <p>
  1. 把类改成面向接口的，实现自接口，并在类名上做可扩展重命名，以id生成的机制来命名，随机id生成器，为以后递增的id生成器作预留
  <p>
  2. 把id的三个部分拆成三个部分，抽到三个变量后分别获取
  <p>
  3. 将随机数生成的代码中不可读的判断条件拆成变量来说明代码表示的意思
  <p>
  4. 将获取hostname的前后两种不同意义的hostname分开命名
  <p>
  二、提高代码的可测试性
  <p>
  1. 将代码由静态代码改为实现接口，面向接口而非实现，第一步已完成
  <p>
  2. generate方法代码实现依赖运行环境（本机名）、时间函数、随机函数，所以其本身可测试性不好，可以把依赖项单独抽出来，将getLastFieldOfHostName方法中的分隔字段的实现抽成getLastSubstrSplitByDot函数，
  因为getLastFieldOfHostName函数依赖本地主机名，所以剥离出主要代码后这个函数变得非常简单，可以不用测试，我们只需要重点测试getLastSubstrSplitByDot即可
  <p>
  三、 编写完善的单元测试
  <p>
  将能测试的功能都抽离出来成单独方法，和非可测试代码分离出来
  <p>
  四、添加注释
  <p>
  注释中主要写清楚：做什么、为什么、怎么做、怎么用，
  对一些边界条件、特殊情况进行说明，以及对输入、输出、异常进行说明
  <p>
  <p>
  alphameric 字母数字的 == alphanumeric
  <p>
  Delimiter 分隔符

  @author sunzhangfei
 * @since 2021/8/12 2:35 下午
 */

/**
 * Id Generator that is used to generate random IDs.
 * <p>
 * The IDs generated by this class are not absolutely unique, but the probability of duplication is very low.
 */
public class RandomIdGenerator implements LogTraceIdGenerator {
    private static final Logger logger = LoggerFactory.getLogger(IdGenerator.class.getSimpleName());

    /**
     * Generate the random IDs. the IDs may be duplicated in extreme situation.
     *
     * @return the random ID, pattern like {hostname}-{timestamp}-{randomstring} (for example: local-230920239019-a28IKo23)
     */
    @Override
    public String generate() {
        String substrHostName = getLastFieldOfHostName();
        long currentTimeMillis = System.currentTimeMillis();
        String randomString = generateRandomAlphameric(8);
        return String.format("%s-%d-%s", substrHostName, currentTimeMillis, randomString);
    }

    /**
     * Get the local hostname and extract the last field of the name string split by delimiter '.'
     *
     * @return the last field of hostname. returns null if hostname is not obtained
     */
    private String getLastFieldOfHostName() {
        String subHostName = null;
        try {
            String hostName = InetAddress.getLocalHost().getHostName();
            subHostName = getLastSubstrSplitByDot(hostName);
        } catch (UnknownHostException e) {
            logger.warn("Unknown host", e);
        }
        return subHostName;
    }

    /**
     * Get the last field of {@hostName} split by delimiter '.'
     *
     * @param hostName should not be null
     * @return the last field of {@hostName}. return empty string if {@hostName} is empty
     */
    @VisibleForTesting
    public String getLastSubstrSplitByDot(String hostName) {
        if (hostName == null || hostName.isEmpty()) {
            throw new IllegalArgumentException("hostName param should not be null");
        }
        String[] tokens = hostName.split("\\.");
        return tokens[tokens.length - 1];
    }

    /**
     * Generate random string which only contains digits, uppercase letters and lowercase letters
     *
     * @param length should not be less than 0
     * @return the random string. Returns empty if {@length} is less than 0
     */
    @VisibleForTesting
    public String generateRandomAlphameric(int length) {
        char[] randomChars = new char[length];
        int count = 0;
        while (count < length) {
            int maxAscii = 'z';
            char randomChar = (char) (Math.random() * maxAscii + 1);
            boolean isDigit = randomChar >= '0' && randomChar <= '9';
            boolean isUpperCase = randomChar >= 'A' && randomChar <= 'Z';
            boolean isLowerCase = randomChar >= 'a' && randomChar < 'z';
            if (isDigit || isLowerCase || isUpperCase) {
                randomChars[count] = randomChar;
                ++count;
            }
        }
        return new String(randomChars);
    }

}